### ISSUE TITLE
SIGSEGV on Qt 6.7.1 environment?

### ISSUE THREAD

**Issue by tsutsui** [eighttails/PC6001VX#17]
PC6001VX 4.2.4 works n NetBSD/i386 10.0 + pkgsrc-2024Q1 (with Qt 6.6.2), but after updating Qt to 6.7.1 (from pkgsrc -current) PC6001VX 4.2.4 gets SIGSEGV on startup:

GDB backtrace shows:
```
Reading symbols from work.i386/PC6001VX_4.2.4_src/PC6001VX...
(gdb) run
Starting program: /usr/pkgsrc/emulators/PC6001VX/work.i386/PC6001VX_4.2.4_src/PC6001VX 
[New LWP 17147 of process 10970]
[New process 10970]
[New LWP 1848 of process 10970]
[New LWP 457 of process 10970]
[New LWP 6877 of process 10970]
[New LWP 22793 of process 10970]

Thread 1 "" received signal SIGSEGV, Segmentation fault.
0xac1abed1 in QObject::deleteLater() () from /usr/pkg/qt6/lib/libQt6Core.so.6
(gdb) bt
#0  0xac1abed1 in QObject::deleteLater() () from /usr/pkg/qt6/lib/libQt6Core.so.6
#1  0x00682d67 in P6VXApp::executeEmulation (this=<optimized out>) at src/Qt/p6vxapp.cpp:829
#2  0x00734b9b in P6VXApp::qt_static_metacall (_o=0xbfb58d88, _c=QMetaObject::InvokeMetaMethod, _id=18, _a=0xa64a0d8c) at moc_p6vxapp.cpp:280
#3  0xac1a9db9 in QMetaCallEvent::placeMetaCall(QObject*) () from /usr/pkg/qt6/lib/libQt6Core.so.6
#4  0xac1aeb44 in QObject::event(QEvent*) () from /usr/pkg/qt6/lib/libQt6Core.so.6
#5  0xac1745b3 in QCoreApplication::event(QEvent*) () from /usr/pkg/qt6/lib/libQt6Core.so.6
#6  0xac9e97f5 in QGuiApplication::event(QEvent*) () from /usr/pkg/qt6/lib/libQt6Gui.so.6
#7  0xad2cf99a in QApplication::event(QEvent*) () from /usr/pkg/qt6/lib/libQt6Widgets.so.6
#8  0xad2c8e5b in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/pkg/qt6/lib/libQt6Widgets.so.6
#9  0xad2d1816 in QApplication::notify(QObject*, QEvent*) () from /usr/pkg/qt6/lib/libQt6Widgets.so.6
#10 0x00688026 in P6VXApp::notify (this=0xbfb58d88, receiver=0xbfb58d88, event=0xa64a0d60) at src/Qt/p6vxapp.cpp:1193
#11 0xac174368 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/pkg/qt6/lib/libQt6Core.so.6
#12 0xac174600 in QCoreApplication::sendEvent(QObject*, QEvent*) () from /usr/pkg/qt6/lib/libQt6Core.so.6
#13 0xac1780b4 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/pkg/qt6/lib/libQt6Core.so.6
#14 0xac178326 in QCoreApplication::sendPostedEvents(QObject*, int) () from /usr/pkg/qt6/lib/libQt6Core.so.6
#15 0xac39e142 in ?? () from /usr/pkg/qt6/lib/libQt6Core.so.6
#16 0xaa362665 in g_main_dispatch () from /usr/pkg/lib/libglib-2.0.so.0
#17 0xaa3652e9 in g_main_context_iterate_unlocked.constprop () from /usr/pkg/lib/libglib-2.0.so.0
#18 0xaa3659d4 in g_main_context_iteration () from /usr/pkg/lib/libglib-2.0.so.0
#19 0xac39d919 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/pkg/qt6/lib/libQt6Core.so.6
#20 0xa657974f in ?? () from /usr/pkg/qt6/lib/libQt6XcbQpa.so.6
#21 0xac17f4dd in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/pkg/qt6/lib/libQt6Core.so.6
#22 0xac17d108 in QCoreApplication::exec() () from /usr/pkg/qt6/lib/libQt6Core.so.6
#23 0xac9de712 in QGuiApplication::exec() () from /usr/pkg/qt6/lib/libQt6Gui.so.6
#24 0xad2c8dd4 in QApplication::exec() () from /usr/pkg/qt6/lib/libQt6Widgets.so.6
#25 0x0075235f in main (argc=<optimized out>, argv=0xbfb58e64) at src/Qt/pc6001v.cpp:83
(gdb) 
```

I'm not sure if this is environment dependent, but I'd like to know if 6.7.1 is tested on other platforms.

**Comment by eighttails** [comment]
Downgraded SingleApplication and confirmed working with Qt6.7.1 in Linux.

**Comment by tsutsui** [comment]
I've confirmed 4.2.7 (with SingleApplication 3.4.1 I guess) works with Qt 6.7.1 on NetBSD/i386 10.0. Thanks!
